# Generated by Django 6.0.2 on 2026-02-28 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuarios',
            old_name='emeil',
            new_name='email',
        ),
    ]
