# Generated by Django 6.0.2 on 2026-02-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_emeil_usuarios_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuarios',
            name='senha',
            field=models.CharField(max_length=128),
        ),
    ]
